[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyansistring"
version = "0.2.0"
dependencies = []
requires-python = ">=3.11"
authors = [
  {name="Volodymyr Horshenin"},
]
description = "A library for string color styling using ANSI escape sequences."
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E*"]
keywords = [
  "ansi", "color", "terminal", "console", "cli", "tui",
  "ansi-colors", "ansi-escape-codes", "terminal-colors", "colored-text",
  "text-formatting", "text-styling", "string-formatting", "colorize",
  "logging", "debugging", "rich-text"
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Topic :: Terminals",
  "Topic :: Text Processing",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: System :: Logging",
  "Environment :: Console",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]

[project.optional-dependencies]
all = [
  "pyansistring[img]",
]
img = [
  "fonttools",
]

[project.urls]
Repository = "https://github.com/l1asis/pyansistring.git"
Issues = "https://github.com/l1asis/pyansistring/issues"

[tool.pytest.ini_options]
addopts = "-v"
testpaths = ["tests"]

[tool.coverage.run]
source = ["pyansistring"]

[tool.coverage.report]
show_missing = true

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.lint.per-file-ignores]
"src/pyansistring/arts.py" = ["E501"]